num_episodes: 10000

single_agent_training: false  # If true, only agent1 will be trained

agents:
  agent1:
    policy_infile: ""
    policy_outfile: "agent1.json"
    alpha: 0.3
    gamma: 0.99
    epsilon: 0.1
    min_alpha: 0.01
    min_epsilon: 0.01
  agent2:
    policy_infile: "agent1.json"
    policy_outfile: "agent2.json"
    alpha: 0.05
    gamma: 0.90
    epsilon: 0.05
    min_alpha: 0.01
    min_epsilon: 0.01
